### ISSUE TITLE
Does not work with CentOS 6

### ISSUE THREAD

**Issue by rickyrockrat** [swick/mozilla-gnome-keyring#22]
Library functions don't exist on Cent OS 6.

How do I add a patch?

**Comment by swick** [comment]
Hi, you fork this repository, write the patches, push them to your repo and then use github to open a pull request. Alternatively you can send me the patch via mail and I'll merge it.

**Comment by rickyrockrat** [comment]
I don't think you want my fork. I had to add a compatibilty library for gnome-keyring because it was missing some important functions - then added those to the code.  It would need to be a branch that never merged to main, I think.

**Comment by swick** [comment]
Hello, again. I'd really appreciate if you could tell me what exactly the problem is. Fixing the addon for other linux based operating systems is definitely a priority for me.
