### ISSUE TITLE
Change default keyring to "mozilla" if it exists

### ISSUE THREAD

**Issue by matthijskooijman** [swick/mozilla-gnome-keyring#32]
After an upgrade, I noticed today all my passwords were gone. Investigating, I found that the keyring to use is now configurable and defaults to "default", whereas it was hardcoded to "mozilla" before. This leads to a bad upgrade experience - everything is gone, without any indication why.

Perhaps it makes sense to instead, if no keyring preference is set and a "mozilla" keyring exists, then default to "mozilla"? I'm not sure how fast people are to upgrade and if this is still relevant (since the change is from April, I think), but I just noticed this today, so I guess this change was only recently released?

**Comment by swick** [comment]
I don't think there is anything I can do about it now, I'll just have to avoid making the same mistake again.
