### ISSUE TITLE
Firefox gets really slow with gnome-keyring enabled

### ISSUE THREAD

**Issue by matthijskooijman** [swick/mozilla-gnome-keyring#33]
I have a large number of secrets in my keyring (about 700, I think). Since today, I noticed my Firefox gets really sluggish when this add-on is enabled. There are frequent slowdowns, each lasting a few seconds (during which Firefox doesn't respond to any input). Slowdowns happen whenever switching tabs, clicking links, interacting with some input fields, possibly in more moments. The slowdowns disappear when I disabe the add-on, or when I switch it to use a nearly empty keyring.

dbus-monitor output shows that the full contents of my keyring is requested 3 times when I switch from one tab to another. Requesting all my keys takes a while, so this probably results in the slowdown. Is requesting the full keyring contents regularly intentional, or should it normally request only what it needs, or cache the results?

This issue is probably introduced when I upgraded the Debian package for this add-on, from version 0.6.11-3 to 0.10-1~deb8u1. When I downgrade again, the problem disappears.

It also seems the Secure Login (version 1.1.5) add-on is involved - if I disable it, the issue disappears as well. It seems likely that that add-on makes requests for secrets to the gnome-keyring add-on, which take a long time to fullfil. I'll file a support request for that add-on too and point it to this ticket as well.

**Comment by matthijskooijman** [comment]
After a bit more usage, I've found that even with secure login disabled, the slowness persists. It just doesn't occur as often, but when I interact with a login form, Firefox hangs for few seconds at some points in the process, leading me to believe that the problem is indeed in the gnome-keyring extensions, and secure login just exposes the problem more thoroughly.

**Comment by swick** [comment]
Could you try f8e4d0e2391e20a128ae203af145467c94341365 and report if this is better?

**Comment by matthijskooijman** [comment]
Yup, seems to work like a charm! Thanks :-D

**Comment by matthijskooijman** [comment]
I just noticed an issue - deleting a password does not seem to work (they are deleted from the list in Firefox, but if I re-open the list, or look in the keyring use Seahorse, they're still present). I haven't tested if this is caused by this patch, or is also broken without it, but it sounds like it could be caused by it?

**Comment by swick** [comment]
Please test 2fde62fcf3835d4b300c9c31e1531851abee2adc

**Comment by matthijskooijman** [comment]
Yup, that fixes deletion of passwords. Spot-on!
