### ISSUE TITLE
Email is not saved in the keyring

### ISSUE THREAD

**Issue by guillaume-uH57J9** [swick/mozilla-gnome-keyring#34]
Hi,

On the following login page, I have provided both an email and password, and confirmed I'd like them saved. This website like many others use email addresses as identifier. 
https://soutien.laquadrature.net/login

However, when going back to the login page, only the password is filled. Upon listing the saved login/password, it appears the username was NOT saved. 

A quick look at the HTML shows it's a relatively standard login form, but that the input type is "input". On most login forms the type "text" is used. 
When changing the input type to "text" (w/ developer tools), the extension is able to remember the login. 

Firefox 38.5.0 (branded as Iceaweasel by Debian)
GNOME Keyring Integration 0.10

**Comment by swick** [comment]
Firefox is behaving the same way without this extension so there is nothing that can be done here. This should be reported to firefox directly.
