### ISSUE TITLE
Cannot delete saved login-password pair from Firefox UI

### ISSUE THREAD

**Issue by guillaume-uH57J9** [swick/mozilla-gnome-keyring#35]
Reproducing: 
* Go to a random random login page, such as http://oyanforum.com/
* Provide a dummy login-password pair, for testing purpose
* Accept to save it
* In the address bar, click on the globe, then "More Information..", and finally "View saved passwords..."
* Delete the saved password
* Close the dialogs, and repeat the previous step to display saved passwords again. The password still appear, whereas I expected it to be gone. 

Gnome Keyring Integration 0.10
Firefox 38.5.0 (branded as Iceweasel)
Debian GNU/Linux

**Comment by swick** [comment]
should be fixed in 2fde62fcf3835d4b300c9c31e1531851abee2adc, can you confirm?

**Comment by guillaume-uH57J9** [comment]
Hi swick, and happy new year

Gnome Keyring Integration 0.11 (which I assume includes 2fde62f) fixes this.

Thanks
