### ISSUE TITLE
Addon is not signed

### ISSUE THREAD

**Issue by R3s1stanc3** [swick/mozilla-gnome-keyring#37]
Hi
I just installed this Addon in Thunderbird and Firefox.
Thunderbird works fine but Firefox tells me that the Addon is not signed and could not be verified.
Can you get it signed by the Firefox Devs?
In the current version it is possible to set xpinstall.signatures.required to false, but this feature won't exist in the next version.

**Comment by swick** [comment]
As far as I understand the process, this addon on addons.mozilla.org is automatically signed and should work just fine.
