### ISSUE TITLE
Get rid of maxVersion

### ISSUE THREAD

**Issue by infinity0** [swick/mozilla-gnome-keyring#43]
Now that the extension is in JS, it should be unnecessary to keep re-compiling it, which (IIRC) was  the original reason for having "maxVersion" in `install.rdf`. It would avoid having to do e.g. #41 all the time, as well as things like [Debian bug 838546](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838546)

What do you think?

**Comment by swick** [comment]
The maxVersion tag is required. Firefox supports the version "*", but Thunderbird does *not*. We could set it to "*" for Firefox but you'd still have to update it for Thunderbird. I don't care about this, so it's your call.

**Comment by infinity0** [comment]
We could set it to `999.*`, I've done that for the Debian package.

**Comment by swick** [comment]
When uploading a xpi file to mozilla.org it checks if the version is actually available and doesn't allow you to distribute the file if it's not. I could manually change the maxVersion on the xpi files, though.

**Comment by d9h02f** [comment]
Maybe a good question is how many people actually use this extension for Thunderbird? There are other email clients which actually integrate with GNOME and are far better than Thunderbird at everything. I'd just drop support for Thunderbird and urge people to get a better email client.

**Comment by infinity0** [comment]
I use this extension for Thunderbird, I'm happy to maintain support for it. It only involves those 3 lines in install.rdf, it's not a big deal. OK, well I'm happy to patch 999 in for Debian (it seems to work for both FF and TB), up to you how you want to do it here.

**Comment by swick** [comment]
Alright. I set maxVersion to 999.* in 56f938d. I'll manually set it when I upload it to mozilla.org.

**Comment by glensc** [comment]
i use for thunderbird and icedove. and what are the "better" mail clients? so far only "better" i found kmail from kde3 which by obvious reasons i can no longer use.

**Comment by glensc** [comment]
https://github.com/swick/mozilla-gnome-keyring/issues/43#issuecomment-249365298

@swick you mention you upload it to mozilla.org, i can not find it there. but i find some other older versions by other people. can you share direct link (put it to readme maybe even?)

with mozilla.org, don't probably even need to maintain [distro version](https://github.com/pld-linux/mozilla-addon-gnome-keyring)
