### ISSUE TITLE
Passwords stored and expected in a format not readable by Epiphany and presumably other browsers

### ISSUE THREAD

**Issue by Pointedstick** [swick/mozilla-gnome-keyring#45]
When Firefox uses this extension to save a password to GNOME Keyring, it saves them in a different format than the one that Epiphany uses. This extension save passwords like this:
```
passwordField: passwd
formSubmitURL: https://www.reddit.com
hostname: https://www.reddit.com
usernameField: user
httpRealm: 
username: <username>
mozLoginInfoMagic: loginInfoMagicv1
```

Epiphany saves it like this:
```
username: <username>
form_password: passwd
uri: http://www.reddit.com/
form_username: user
```

Here's what it looks like visually:

![both keys 1](https://cloud.githubusercontent.com/assets/1097249/20504783/8e53c302-b006-11e6-8bb8-81a416894274.png)
![both keys 2](https://cloud.githubusercontent.com/assets/1097249/20504784/8e54c388-b006-11e6-9389-64f9e191e935.png)

Neither browser is able to understand the format used by the other, defeating the purpose of using a systemwide utility to store passwords. This extension should adopt the Epiphany format for the copy that it exports to GNOME Keyring.

Note: I have also filed a bug on the GNOME folks in case they're the ones Doing It Wrong:™ https://bugzilla.gnome.org/show_bug.cgi?id=774820

**Comment by swick** [comment]
I doubt that it makes sense to work on this. The xpcom framework is being deprecated and there doesn't seem to be a replacement for implementing an alternative login storage. I'll keep maintaining this addon for as long as people use firefox with xpcom addons but if you want to solve this problem I suggest bringing it up to the firefox devs.

**Comment by Pointedstick** [comment]
Darn. Well, thanks for the info anyway. Guess I'm switching to Chromium.
