### ISSUE TITLE
Stopped working (in Firefox 51?)

### ISSUE THREAD

**Issue by FMITBugReport** [swick/mozilla-gnome-keyring#47]
It worked fine for a long time, but since a while (possibly since last Firefox update, but not sure), the keyring does not seem to be accessible any more from Firefox. Logins are not filled automatically, and no saved passwords appear in Preferences->Security->Saved Logins. Also the Add-On preferences of mozilla-gnome-keyring do not list the available key rings.

Under Thunderbird all works as before.

I am using Xubuntu 16.04 LTS (32 bit).

**Comment by swick** [comment]
I cannot reproduce this. Can you narrow this down to a addon or firefox version? Does it work in a fresh profile?

**Comment by FMITBugReport** [comment]
My exact Firefox version is 51.0.1 (32-bit), GNOME Keyring integration 0.12, and kernel 4.4.0-64-lowlatency. No difference if I boot with the generic kernel.

But on this same machine the keyring integration works as expected if I boot into another Linux installation on a separate drive (same Firefox, same kernel, same keyring add-on), so something must have changed with this particular set-up (as it was working until a few weeks ago).

I attach a screen shot of the add-on window. It appears that it does not see the keyring at all. I do have a default keyring (checked in Seahorse), and I also tried adding a new ring, but the add-on still does not see it. 

Other things I tried without effect: reinstall Firefox, remove and install GNOME Keyring integration.

I think the keyring as such is OK, as GNOME Keyring integration in Thunderbird continues to work as before. 

![screenshot_2017-02-23_22-16-12](https://cloud.githubusercontent.com/assets/16050452/23279917/7084ac50-fa17-11e6-9dac-75dd933f360a.png)

**Comment by FMITBugReport** [comment]
I now also tried with a fresh profile in Firefox, with the same result: after installing the GNOME Keyring Integration add-on in the new profile, it does not show a keyring, as seen in the previous screen shot.

**Comment by FMITBugReport** [comment]
The issue is related to AppArmor.

Starting Firefox in a terminal, the following message is shown when opening the preferences of GNOME Keyring Integration:
`Gkr-Message: secret service operation failed: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.173" (uid=1000 pid=5976 comm="/usr/lib/firefox/firefox ") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.freedesktop.secrets" (uid=1000 pid=1736 comm="/usr/bin/gnome-keyring-daemon --daemonize --login ")`

After disabling the Firefox AppArmor profile the add-on is working again.

Could this be related to [this bug](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1659988)?

It's thus not really a bug with GNOME Keyring Integration. I vaguely recall there was indeed an update recently related to AppArmor, which might have resulted in this problem.
