### ISSUE TITLE
appears to be corrupt

### ISSUE THREAD

**Issue by rkouznetsov** [swick/mozilla-gnome-keyring#58]
$ git clone https://github.com/swick/mozilla-gnome-keyring.git mozilla-gnome-keyring
$ cd mozilla-gnome-keyring
$ make

Then the file gnome-keyring-integration.xpi appears in the bin drectory.

When attempting to install add-on to firefox 68.0.2 (64-bit) from Ubuntu 18.04,
it claims that "This add-on could not be installed because it appears to be corrupted"

Any ideas?

**Comment by rkouznetsov** [comment]
When trying to install temporary from about:debug page it fails with an error 
"There was an error during installation: File" ...  "mozilla-gnome-keyring/bin/gnome-keyring-integration.xpi does not contain a valid manifest"

**Comment by Glandos** [comment]
Firefox 68 does not support this extension, which uses old API that are not available anymore.

This won't work.

**Comment by swick** [comment]
Duplicate of #48
